community_name: ceheroku
support_email:  "admin@curbly.com"

photo:
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "100x100", medium: "290x320", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 's3'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
      
feature:
  use_thumbs: true
  dimensions: [150, 635]
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 1
    thumbnails: {thumb: '45x45', large: '635x150'}    
    storage: 's3'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
        
clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 3
    thumbnails: {thumb: "100x100", medium_square: "200x200", medium: "200>"}
    storage: 's3'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']